name: CI

on:
  push:
    branches:
      - develop
      - release
      - main
      - feature/auto-tests
  pull_request:
    branches:
      - develop
      - release
      - main
      - feature/auto-tests
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test:unit
